SELECT ?club ?clubLabel ?stadium ?stadiumLabel ?capacity ?coord WHERE {

  {
    SELECT DISTINCT ?club WHERE {
      wd:Q139940116 wdt:P710 ?club.
    }
  }

  OPTIONAL {
    ?club wdt:P115 ?stadium.
    OPTIONAL { ?stadium wdt:P1083 ?capacity. }
    OPTIONAL { ?stadium wdt:P625 ?coord. }
  }

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "pl,en".
  }
}
ORDER BY ?clubLabel